version: '2'

services:
    nginx:
        image: nginx:1.13.6
        container_name: data-filter-nginx
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: data-filter-php
        expose:
            - 9000
        volumes:
            - .:/var/www/html
        links:
            - postgres

    postgres:
        image: postgres:10.4-alpine
        container_name: data-filter-postgres
        ports:
            - "54321:5432"
        volumes:
            - ~/.backup/postgres/laravel/data_filter:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=data_filter

    redis:
        image: redis:5.0.5
        ports:
            - "6379:6379"
        volumes:
            - ~/.backup/redis/laravel/data_filter:/data
